- name: Configure Erlang repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure RabbitMQ Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq/raq-server/script.rpm.sh | bash

- name: Install RabbitMQ Server
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure priv: .*
    read priv: .*
    write priv: .*
    state: present