- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: Roboshop

- name: Setup app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract the App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes

- name: Download and build software
  ansible.builtin.shell: npm install
  args:
       chdir: /app


- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes