- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Setup app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract the App Content
  ansible.builtin.unarchive:
    src:  curl -L -o /tmp/dispatch.zip https://roboshop-artifacts.s3.amazonaws.com/dispatch.zip
    dest: /app
    remote_src: yes

- name: Start {{ component }} Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes