- name: Install Mysql Client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: load Schema
  ansible.builtin.shell: mysql -h mysql.devops2406.xyz -uroot -pRoboshop@1 </app/schema/{{ component }}.js
